import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import S from "./styles.module.scss";

const pretendard = localFont({
  src: [
    {
      path: "../fonts/Pretendard-Regular.woff2",
      weight: "400",
      style: "regular",
    },
    {
      path: "../fonts/Pretendard-Regular.woff",
      weight: "400",
      style: "regular",
    },
    {
      path: "../fonts/Pretendard-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    { path: "../fonts/Pretendard-Medium.woff", weight: "500", style: "medium" },
    {
      path: "../fonts/Pretendard-SemiBold.woff2",
      weight: "600",
      style: "semi bold",
    },
    {
      path: "../fonts/Pretendard-SemiBold.woff",
      weight: "600",
      style: "semi bold",
    },
    { path: "../fonts/Pretendard-Bold.woff2", weight: "700", style: "bold" },
    { path: "../fonts/Pretendard-Bold.woff", weight: "700", style: "bold" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className}`}>
        <div className={S.pageLayout}>{children}</div>
      </body>
    </html>
  );
}
